homeassistant:
  name: Home
  latitude: !secret zone_home_lat
  longitude: !secret zone_home_lon
  elevation: 596
  unit_system: metric
  time_zone: America/Monterrey
  #customize_domain:
  #  zwave:
  #    hidden: true
  customize: !include_dir_merge_named customizations

frontend:

config:

http:
  api_password: !secret api_password
  # base_url: example.duckdns.org:8123

updater:
  include_used_components: true

discovery:

conversation:

shopping_list:

history:

logbook:
  exclude:
    entities:
      - automation.zwave_refresh
      - zwave.movitres
      - zwave.puertabalcon
      - zwave.puertalavanderia
      - zwave.puertapatioder
      - zwave.puertapatioizq
      - zwave.ventanacocina
      - zwave.ventanaestancia

logger:
  default: info
  logs:
    homeassistant.components.mqtt: debug

recorder:
  purge_interval: 1
  purge_keep_days: 14

sun:

binary_sensor:
  - platform: bloomsky
    monitored_conditions:
      - Night
      - Rain

# Text to speech
tts:
  - platform: google
    language: 'es'

zwave:
  usb_path: /dev/ttyACM0

light:
  - platform: lifx

bloomsky:
  api_key: !secret bloomsky_api_key

media_player:
  - platform: cast

device_tracker:
  - platform: gpslogger

group: !include groups.yaml
automation: !include_dir_merge_list automations
script: !include scripts.yaml
sensor: !include_dir_merge_list sensors
notify: !include_dir_merge_list notifications

cuby:
  username: !secret cuby_username
  api_key: !secret cuby_api_key

wink:

zone:
  - name: Colinas
    latitude: !secret zone_colinas_lat
    longitude: !secret zone_colinas_lon
    radius: 100
    icon: mdi:home-outline
  - name: Altavista
    latitude: !secret zone_altavista_lat
    longitude: !secret zone_altavista_lon
    radius: 100
    icon: mdi:home-outline
  - name: CyA
    latitude: !secret zone_cya_lat
    longitude: !secret zone_cya_lon
    radius: 200
    icon: mdi:panda
  - name: Formus
    latitude: !secret zone_formus_lat
    longitude: !secret zone_formus_lon
    radius: 200
    icon: mdi:panda

mqtt:
  broker: !secret mqtt_broker
  port: !mqtt_port
  client_id: home-assistant-paseo
  username: !secret mqtt_username
  password: !secret mqtt_password
