- platform: template
  sensors:
    alarmauno_status:
      value_template: >-
          {%- if is_state("sensor.alarmauno_alarm_type", "13") %}
              Clear
          {%- elif is_state("sensor.alarmauno_alarm_type", "1") %}
              Smoke
          {%- elif is_state("sensor.alarmauno_alarm_type", "2") %}
              CO
          {%- elif is_state("sensor.alarmauno_alarm_type", "12") %}
              Test
          {% else %}
              Unknown
          {%- endif %}
      friendly_name: 'Alarma Humo/CO Uno'

- platform: template
  sensors:
    alarmauno_battery_level:
      value_template: '{{states.sensor.alarmauno_alarm_type.attributes.battery_level}}'
      friendly_name: 'Alarma Humo/CO Uno Batería'
      unit_of_measurement: '%'
