- alias: 'Cochera ON'
  trigger:
    platform: time
    at: '18:15'
  action:
    service: light.turn_on
    entity_id:
      - light.cochera_level
    data:
      brightness: 128

- alias: 'Cochera OFF'
  trigger:
    platform: time
    at: '06:50'
  action:
    service: light.turn_off
    entity_id:
      - light.cochera_level
