- alias: 'Patio OFF'
  trigger:
    platform: time
    at: '6:35'
  action:
    service: light.turn_off
    entity_id:
      - light.patio_level

- alias: 'Patio ON'
  trigger:
    platform: time
    at: '20:03'
  action:
    service: light.turn_on
    entity_id:
      - light.patio_level
    data:
      brightness: 252

- alias: 'Patio DOWN'
  trigger:
    platform: time
    at: '21:45'
  action:
    service: light.turn_on
    entity_id:
      - light.patio_level
    data:
      brightness: 96
