- alias: 'Recibidor OFF'
  trigger:
    platform: time
    at: '6:45'
  action:
    service: light.turn_off
    entity_id:
      - light.recibidor_level

- alias: 'Recibidor ON'
  trigger:
    platform: time
    at: '18:45'
  action:
    service: light.turn_on
    entity_id:
      - light.recibidor_level
    data:
      brightness: 252

- alias: 'Recibidor DOWN'
  trigger:
    platform: time
    at: '22:00'
  action:
    service: light.turn_on
    entity_id:
      - light.recibidor_level
    data:
      brightness: 64
