- alias: 'Z-wave REFRESH'
  hide_entity: true
  initial_state: 'on'
  trigger:
    platform: time
    minutes: '/1'
    seconds: 00
  action:
  - service: zwave.refresh_entity
    data:
      entity_id: climate.termostatoprincipalz_cooling_1
  - service: zwave.refresh_entity
    data:
      entity_id: light.cochera_level
  - service: zwave.refresh_entity
    data:
      entity_id: light.focorecamarader_level
  - service: zwave.refresh_entity
    data:
      entity_id: fan.abanicorecamarader_level
  - service: zwave.refresh_entity
    data:
      entity_id: fan.abanicorecprincipal_level
  - service: zwave.refresh_entity
    data:
      entity_id: fan.abanicosalaz_level
  - service: zwave.refresh_entity
    data:
      entity_id: switch.escaleras_switch
  - service: zwave.refresh_entity
    data:
      entity_id: switch.sala
